version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  app:
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - ${APP_PORT}:3000
    command: sh -c "yarn && yarn build && yarn start:dev"
    depends_on:
      - db
